### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by nbbaier** [BryceRussell/astro-remark-description#1]
Would be great to get a demo of this plugin - having trouble getting it to work.

**Comment by BryceRussell** [comment]
Hey @nbbaier, what does your config look like? There are some [examples in the README](https://github.com/BryceRussell/astro-remark-description#examples) for configuring the plugin, although it should also work without having to configure anything

**Comment by nbbaier** [comment]
Hey, thanks for the reply! I actually figured it out, I had a complete brain glitch and forgotten to include `frontmatter.description` somewhere in my layout so it wasn't showing up. Silly me.
