### ISSUE TITLE
Which licence is this project released under?

### ISSUE THREAD

**Issue by thibaultamartin** [BryceRussell/astro-remark-description#3]
This plugin seems to be particularly useful for what I want to do with Astro, but I didn't see any licence for it?

https://choosealicense.com/licenses/ can be a good start to pick a licence.

**Comment by BryceRussell** [comment]
Good catch! The `package.json` specifies a MIT license but I forgot to add a `LICENSE` file to the repo, I am adding it now.

**Comment by BryceRussell** [comment]
Ok, I added a MIT license to the repo. Thanks for reminding me about this!
